### PR TITLE
Nthaniel

### PR DESCRIPTION
**Pull request by nthaniel**
3 commits: add profile and settings tests; fix videoPlayer test; add test plan suite

### CODE REVIEW

**Comment by nthaniel** [comment]
@mondiaz could you review these tests, please? Thank you!

**Comment by mondiaz** [comment]
@nthaniel Loggedin and Loggedin2 both still contain the base URL line in the code.

+<link rel="selenium.base" href="https://lagunita.stanford.edu/" />

Not sure if that's intentional, just noting it while thinking of it. Will run tests as is and comment further after.

**Comment by mondiaz** [comment]
@nthaniel For the Settings and Profile tests, should these also be checking the following things?
 - for Settings: that adding a birth date over a certain age enables you to add a profile photo and display it to others.
 - for Profile: that you can change to full or limited profile (if you've added a birth date over a certain age)
 - for Profile: that you can add a photo, have it display properly, remove it, replace it

**Comment by mondiaz** [comment]
Changing the settings file to be Settings.html enabled that test case to work properly.

**Comment by mondiaz** [comment]
For the Test Plan Suite, it seems like it would be good to clarify the comment instructions and also to add a pause to the LoggedIn2 test case before the command "verifyVisible" for target "css=#feedback_success_wrapper > p".  You also mentioned that you will make the RegistrationFlow test case more stage/prod friendly by updating the verifyLocation targets.

**Comment by mondiaz** [comment]
LCO-146 #start-progress

**Comment by mondiaz** [comment]
LE-566 #start-review

**Comment by mondiaz** [comment]
LCO-146 #in-review Sorry for all the comments, just trying to get the JIRA + GitHub integration to update the ticket for me.

**Comment by mondiaz** [comment]
@nthaniel Feel free to let me know after you make changes so I can test again. In order to update the JIRA ticket fwiw, add comments to your commits in this format: 

TEST-1 #in-progress #comment performed work 

So:

LCO-146 "in-progress #comment and whatever you want to say here should show up as a comment in the JIRA ticket and also this should update the JIRA ticket's status

**Comment by mondiaz** [comment]
@nthaniel For the Certs test, it failed on me three times in a row after the second command (click link=Register for Feature). When I changed the command to clickAndWait, then it was able to move on smoothly. Test speed didn't seem to matter. 

The four refreshAndWait commands might be better handled by a long pause after the initial clickAndWait to get to the account dashboard.

**Comment by nthaniel** [comment]
@mondiaz I think I've fixed everything now. A couple of notes:

– I decided to leave the refreshAndWait commands as is in the Cert test. It seems functionally the same as pausing for ten seconds and then refreshing, and it feels more accurate to how actual users behave (or at least how I do).
– It turns out the profile pic can't be tested. I uploaded one, but as soon as you change your age to undefined or <13, it disappears for good. So we can either test that profile pics are persistent, or we can test that profiles are limited until you set an age. I think the latter is more important, so that's what I've added to the Profile test.
– The Test Plan suite can't be tested on Stage right now – /courses has no tiles, and other stuff might be broken too. But I think I've caught everything that is prod-specific.

**Comment by mondiaz** [comment]
Neat, everything works for me now in both the main Selenium suite and the test plan suite. :+1:

**Pull request merged**
