### PR TITLE
LE-506 Several minor target updates

### PR DESCRIPTION
**Pull request by mondiaz**
Due to updated CSS selectors and classes post-merge with upstream, we
need to update our Selenium tests accordingly.  This accounts for all
these needed changes, though we should hold off on merging this update
until we’ve released to prod, and can test / verify these changes
there.

### CODE REVIEW

**Comment by mondiaz** [comment]
testing that this affects the status of le-506

**Comment by mondiaz** [comment]
I made a few additional updates (missed some input.* classes and corrected a couple of other things for improved test handling).

**Comment by mondiaz** [comment]
We've merged from upstream now and have released to prod with these and a few additional changes.  @nthaniel Could you review my pull request and confirm that the tests work for you on stage and prod?

**Comment by nthaniel** [comment]
LGTM!

**Pull request merged**
